version: 2.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: 
          name: RunTests
          command: |
            cd src && go test ./...


